"""add fk

Revision ID: 76819d7672d6
Revises: bc1ea0269752
Create Date: 2022-04-17 17:32:45.814303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76819d7672d6'
down_revision = 'bc1ea0269752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('address_user_fk', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
